Import('normal')

check = normal.Program(target  = 'wisp_tests',
                       source  = 'wisp_tests.c',
                       LIBS = ['gmp', 'wisp'],
                       LIBPATH = ['../lib'])

check_alias = normal.Alias('check', check, check[0].path)
normal.AlwaysBuild(check_alias)
